- errors.go
- errors_test.go
Sometimes they happen to contain format specifiers, which results in
things like "%!v(MISSING)".
> Don't pass arbitrary strings as Errorf() format strings.

- errors.go
Fix for #8.
All existing tests still pass, and I have tested this against both scenarios mentioned in issue #8 but I cannot think of a convenient way to test the issue directly from within this repository. We could potentially do a bunch of file manipulations to generate a package structure in a temporary folder and run the test as a child process, but that might be going too far. Thoughts?
> Infer compile time GOPATH from fn.Name().

- errors.go
Remove the errors.e type to make it impossible to type assert an error returned from Wrap{,f} or New.
Instead add behaviours to extract the Cause and the Message and use those in {F,}Print rather than hard coding the magic error.e type.
Also, these helper methods inline, so come at no cost.
> Remove the errors.e type

- errors.go
- errors_test.go
- example_test.go
> Add Errorf

- README.md
Note there's inconsistency on the casing of `causer` in the README and function documentation.
> README.md: "nor" -> "not", backtick causer

- errors.go
> errors.go: "nor" -> "not" (typo fix)

- errors.go
errors.Print had a number of problems. Firstly, it was hard coded to
print to os.Stderr, which made it difficult to test, and hard to write
an example test for. Secondly, comments made in issue #20 make it clear
that helpers need to have a high bar for inclusion in this package, and
something that wrapped errors.Fprint in a way that was hard to test
fails that bar.
So, Remove errors.Print, which frees the identifier for being reused
later, and reduces the size of the package.
> Remove errors.Print

- README.md
- errors.go
- errors_test.go
Store up to 32 stack frames for the caller to New, Errorf, Wrap, and
Wrapf.
> Store the stack of the caller to New, Errorf, Wrap and Wrapf

- errors.go
- errors_test.go
Fixed #29
errors.New, etc values are not expected to be compared by value but
the change in errors#27 made them incomparable. Assert that various
kinds of errors have a functional equality operator, even if the
result of that equality is always false.
> Make errors.stack comparable

- errors.go
renamed `cause` to `err` as per #32
> renamed `cause` argument to `err` - fixes #32

- README.md
- errors.go
- errors_test.go
- example_test.go
- stack.go
- stack_test.go
This PR is a continuation of a series aimed at exposing the stack trace
information embedded in each error value. The secondary effect is to
deprecated the `Fprintf` helper.
Taking cues from from @chrishines' `stack` package this PR introduces a
new interface `Stacktrace() []Frame` and a `Frame` type, similar in
function to the `runtime.Frame` type (although lacking its iterator
type). Each `Frame` implemnts `fmt.Formatter` allowing it to print
itself.
The older `Location` interface is still supported but also deprecated.
> Introduce Stacktrace and Frame

- errors.go
- example_test.go
- format_test.go
Replace `Fprintf` with `fmt.Formatter` logic on various types. This
effectively guts `Fprint` to be just a recursive call down the `err.Cause()`
chain. The next step will be to move this recursive logic into
`wrapper.Format`.
This change necessitates adding types for the error implementations returned from
`New` and `Errorf`, and `Wrap` and `Wrapf`, respectively. The name of the latter
type is acceptable, the former is not and alternative suggestions are
encouraged.
> Use fmt.Formatter throughout

- errors.go
- errors_test.go
- example_test.go
Fprint should match the stack output, innermost error first.
It probably doesn't matter as Fprint is going away.
> Reverse the order of Fprint output

- errors.go
- errors_test.go
- format_test.go
This PR follows on from #40 completely implementing Fprint in terms of
fmt.Fprintf. This will be the final PR before Fprint is removed.
> Reimplement Fprint in terms of fmt.Fprintf

- errors.go
- errors_test.go
- example_test.go
This PR removes the `Fprint` wrapper and updates all examples to use `fmt.Printf`.
> Remove Fprint

- example_test.go
- stack.go
- stack_test.go
Introduce a new type to replace the unnamed return value from
`Stacktrace()`. `Stacktrace` implements `fmt.Formatter` and currently
replicates the default behaviour of printing a `[]Frame`.
In a future PR the values of `%+v` and `%#v` will be extended to
implement a more readable stacktrace.
> Introduce errors.Stacktrace

- errors.go
- example_test.go
- format_test.go
- stack.go
- stack_test.go
This PR introduces an "extended" stacktrace output to this package's error implementation controlled by the `%+v` verb.
An example of the `%+v` syntax, taken from `ExampleWrap`
```
hello world
github.com/pkg/errors_test.ExampleCause_extended.func1.1
/home/dfc/src/github.com/pkg/errors/example_test.go:156
github.com/pkg/errors_test.ExampleCause_extended.func1
/home/dfc/src/github.com/pkg/errors/example_test.go:157
github.com/pkg/errors_test.ExampleCause_extended
/home/dfc/src/github.com/pkg/errors/example_test.go:158
testing.runExample
/home/dfc/go/src/testing/example.go:114
testing.RunExamples
/home/dfc/go/src/testing/example.go:38
testing.(*M).Run
/home/dfc/go/src/testing/testing.go:744
main.main
github.com/pkg/errors/_test/_testmain.go:104
runtime.main …
```
> Extended stacktrace output

- errors.go
- example_test.go
- stack.go
- stack_test.go
> Rename Stacktrace to StackTrace

- errors.go
- example_test.go
Replacement for #55 
/cc @kr @seh
> Rename StackTrace interface to stacktracer in docs and examples

- errors.go
- format_test.go
Not handling the %q format causes logrus to log empty error strings for
wrapped errors where x.Error() contains spaces or other quoteworthy
characters.
For reference, the logrus formatter does this:
https://github.com/Sirupsen/logrus/blob/master/text_formatter.go#L154
> Fix %q format for wrapped errors

- errors.go
- example_test.go
- stack_test.go
For consistency reasons I thought I would capitalise the first letter of the remaining 'traces' seeing as `Stacktrace` has now been changed to `StackTrace`.
> Capitalise first letter of trace.

- README.md
- errors.go
> Documentation improvements

- bench_test.go
Cost is roughly 1600 ns to 6000 ns depending on the stack size. Adds two additional allocations.
BenchmarkErrors/pkg/errors-stack-10-4         	 1000000	      1676 ns/op	     320 B/op	       3 allocs/op
BenchmarkErrors/errors-stack-10-4             	20000000	        64.9 ns/op	      16 B/op	       1 allocs/op
BenchmarkErrors/pkg/errors-stack-100-4        	  500000	      3058 ns/op	     320 B/op	       3 allocs/op
BenchmarkErrors/errors-stack-100-4            	 3000000	       472 ns/op	      16 B/op	       1 allocs/op
BenchmarkErrors/pkg/errors-stack-1000-4       	  200000	     10685 ns/op	     320 B/op	       3 allocs/op
BenchmarkErrors/errors-stack-1000-4           	  300000	      4523 ns/op	      16 B/op	       1 allocs/op
Fixes #72
> errors: add a benchmark comparing stack trace performance

- stack_test.go
Fixes #77 
This should fix #77 .. I've tested it vendored and unvendored locally. I'm not sure what other tests you'd like to run.
> Modify TestTrimGOPATH to ensure tests pass while vendored

- errors_test.go
- example_test.go
- format_test.go
- stack_test.go
I don't know about the discussions but I like the API additions, so I took a stab at adding some tests.
Adds `testFormatCompleteCompare` as additional testing func. The new function takes a string slice as `want`, wherein stacktraces and non-stacktrace messages are discerned by `strings.ContainsAny(want[i], "\n")`. For example usage, see `TestFormatWithStack` & `TestFormatWithMessage`.
https://github.com/pkg/errors/pull/76 I do not understand the third todo, I thought causer and stack-tracer are separate interfaces so I'm a little bit confused. Is it supposed to add  `NearestCauseWithStackTrace()` or some similar function?
> Add WithStack and WithMessage tests

- errors.go
- format_test.go
- stack.go
- stack_test.go
This PR is extracted from #76 
This PR is a result of the discussions at GopherCon. The focus of the branch is to decompose `Wrap` (and `Wrapf`) into their component operations, namely adding a message, `errors.withMessage` and adding a stack trace, `errors.withStack` which were previously merged into one operation with Wrap.
This is accomplished by rewriting `Wrap` and `Wrapf` to work in terms of these operations although a small deviation is present to make sure the recorded stack trace is correct.
The motivation for this change was need to treat each of the following operations as distinct:
- Adding a context message to an existing error without altering the stack trace.
- Adding a stack trace to an existing error without the requirement adding and additional message.
- Retrieving the …
> Refactor withMessage/withStack

- errors.go
- format_test.go
It looks like pretty much this code was added as part of cbd18b5440315aa74a17dee2e50b67675b872b49 which appears to have been lost while merging #81
> Fix the %q format for errors so it puts "" around the output

- errors.go
- errors_test.go
- example_test.go
- format_test.go
- stack_test.go
This PR is a result of the discussions at GopherCon. The focus of the branch is to decompose Wrap (and Wrapf) into their component operations, namely adding a message, `errors.WithMessage` and adding a stack trace, `errors.WithStack` which were previously merged into one operation with Wrap.
This is accomplished by adding two top level functions, `errors.WithMessage` and `errors.WithStack` and rewriting Wrap and Wrap to work in terms of these operations although a small deviation is present to make sure the recorded stack trace is correct.
The motivation for this change was need to treat each of the following operations as distinct:
- Adding a context message to an existing error _without_ altering the stack trace.
- Adding a stack trace to an existing error _without_ the requirement …
> Destructure Wrap/Wrapf into component operations

- bench_test.go
`toperr` is not used, but the go compiler itself doesn't detect this
because it's within an anonymous function. However, go/types does
detect this as being unused, which causes any static analysis tools
which uses go/types' type checker to fail with the message "toperr
assigned and not used".
The final result of the benchmarked function is instead assigned to
an exported global variable to ensure the compiler cannot now, nor
in the future optimise away the function calls due to no observable
side effects.
It was chosen to assign the final result, after the benchmark loop,
to the global variable, as this best follows the example set in the
CL https://go-review.googlesource.com/#/c/37195/. As opposed to
having each call to f assign to the global. This also appears to
better align with the …
> Move benchmark assigned err to global exported variable

- stack.go
https://goreportcard.com/report/github.com/pkg/errors
Currently, there is only one issue on the report for github.com/pkg/errors above. This PR fixes that issue, which was an undocumented, but exported, Format function.
> Add doc comment for exported Format func

- format_test.go
Found this by https://github.com/mvdan/unparam
I just found it when I try using unparam and run it against packages under $GOPATH randomly.
So, please just close it if you think it's too trivial.
> Remove an unused argument of utility test func

- README.md
Thanks for the great package! Do you have any interest in adding this badge that shows how many people depend on it? It is a nice signal of quality.
Looks like this:
More info:
https://text.sourcegraph.com/see-how-many-people-use-your-library-with-sourcegraph-badges-9750e56e7b2f#.xre5fottq
No problem if you don't want it, but wanted to offer.
> Add badge for number of dependent libraries

- errors.go
- errors_test.go
WithMessagef utility function to accompany WithMessage, similar to
exiting Wrapf function accompanying Wrap.
> Add WithMessagef function

- errors.go
Remove spurious words, add missing words, and smooth out a few sentences.
I didn't edit any of the function- or type-level documentation in this pass.
> Copyedit the package documentation

- errors.go
`errors.go` needed formatting.
> gofmt -w errors.go

- .travis.yml
Remove support for Go 1.8 and earlier as they are
a. no longer supported upstream
b. lack support for runtime.CallerFrames
> travis: remove Go 1.8 and earlier

- stack.go
`errors.Frame` is convertible from/to a `runtime.Frame` and knows how to print itself.
> Remove Frame methods

- bench_test.go
- stack.go
This implements proposal in #149 by adding a format method to `Frame` that accepts an `io.Writer`, allowing `stack` and `StackTrace` to grow a `bytes.Buffer` ahead of time. The benefits are illustrated in the benchmark comparison below, in summary allocations are reduced by 90-97% resulting in a 40-55% performance boost.
This comes at a slight cost in bytes used, which is around 5% higher on average with a single case reaching 36% (small stack, %s) which is probably not worth special casing. This trade off can be affected by adjusting stackMinLen with a more generous multiplier, lowering allocations at the expense of unused buffer.
```
benchmark                                         old ns/op     new ns/op     delta
BenchmarkStackFormatting/%s-stack-10-24           411           402 …
```
> reduce allocations when printing stack traces (#149)

- Makefile
Remove deprecated linters that have been rolled into staticcheck.
> Makefile: switch to staticcheck

- stack.go
Avoid the unnecessary conversions from errors.Frame to
runtime.Frame to access the latter's fields as by definition the former
also has the same fields.
> Remove errors.Frame to runtime.Frame conversions

- format_test.go
- stack.go
With Go 1.12, we will now be doing mid-stack inlining. This exposes
inlined frames to runtime.Callers and friends.
The spec says that a runtime.Frame may have a nil Func field for
inlined functions. Instead, use the Function field to detect whether
we really have an empty Frame.
> errors: detect unknown frames correctly

- format_test.go
- stack.go
- stack_test.go
Updates aws/aws-xray-sdk-go#77
Updates evalphobia/logrus_sentry#74
Go 1.12 has updated the behaviour of runtime.FuncForPC so that it
behaves as it did in Go 1.11 and earlier.
This allows errors.Frame to return to a uintptr representing the PC +1
of the caller. This will fix the build breakages of projects that were
tracking HEAD of this package.
> Return errors.Frame to a uintptr

- stack.go
- stack_test.go
Updates #150
```
benchmark                                        old allocs     new allocs     delta  
BenchmarkErrors/pkg/errors-stack-10-8            3              3              +0.00% 
BenchmarkErrors/errors-stack-10-8                1              1              +0.00% 
BenchmarkErrors/pkg/errors-stack-100-8           3              3              +0.00% 
BenchmarkErrors/errors-stack-100-8               1              1              +0.00%
BenchmarkErrors/pkg/errors-stack-1000-8          3              3              +0.00%
BenchmarkErrors/errors-stack-1000-8              1              1              +0.00%
BenchmarkStackFormatting/%s-stack-10-8           1              1              +0.00%
BenchmarkStackFormatting/%v-stack-10-8           1              1              +0.00% …
```
> Reduce allocations in Stacktrace.Format

- json_test.go
- stack.go
Fixes #196
This PR adds `json.Marshaler` support for the `Frame` type, to facilitate logging of stack traces in JSON format.  The output format is equivalent to `fmt.Printf("v+%")`, but without newlines or tab characters.
To me, this format seems the most generally useful, but an argument could be made for outputting a JSON object instead (i.e. `{"file":"...", "line": XX, "name": "..."}`.).
> Add json.Marshaler support to the Frame type.

- .travis.yml
> travis.yml: add Go 1.12

- .travis.yml
- README.md
> travis.yml: add Go 1.13

- cause.go
- errors.go
- go113.go
- go113_test.go
Imagine module A imports module B and both use `pkg/errors`. A uses
`errors.Cause` to inspect wrapped errors returned from B. As-is, B
cannot migrate from `errors.Wrap` to `fmt.Errorf("%w", err)` because
that would break `errors.Cause` calls in A. With this change merged,
`errors.Cause` becomes forwards-compatible with Go 1.13 error chains.
Module B will be free to switch to `fmt.Errorf("%w", err)` and that will
not break module A (so long as the top-level project pulls in the newer
version of `pkg/errors`).
> Support Go 1.13 error chains in `Cause`
